[View in Colaboratory](https://colab.research.google.com/github/ditiansm2015/ML-May-28/blob/master/assignment_2.ipynb)

SUDHANSHU MISHRA

Machine Learning with Python (SUM18 ML ON1)

ASSIGNMENT_2

In [52]:
#Question_1
#mean of elements

import numpy as np

narray=np.random.rand(10,1)
print("Array elements are\n",narray)

mean_narray=np.mean(narray)
print("\nMean:",mean_narray)


Array elements are
 [[0.45929053]
 [0.21861718]
 [0.51370996]
 [0.55581157]
 [0.3583289 ]
 [0.84773718]
 [0.68414497]
 [0.91386578]
 [0.05821804]
 [0.86781308]]

Mean: 0.5477537192437568


In [53]:
#Question_2
#Variance and Standard Deviation

import numpy as np

narray=np.random.rand(20,1)
print("Array elements are\n",narray)

variance_narray=np.var(narray)
print("\nVariance is:",variance_narray)

sd_narray=np.std(narray)
print("Standard Deviation:",sd_narray)

Array elements are
 [[0.20541873]
 [0.13956423]
 [0.65918159]
 [0.67293322]
 [0.97945114]
 [0.78253028]
 [0.49127622]
 [0.90125211]
 [0.72870035]
 [0.41515181]
 [0.2647452 ]
 [0.98234089]
 [0.01381087]
 [0.85620206]
 [0.84073948]
 [0.83016735]
 [0.16830154]
 [0.73509994]
 [0.01294845]
 [0.56644313]]

Variance is: 0.1003929424211915
Standard Deviation: 0.3168484533987684


In [54]:
#Question 3
#matrx multiplication and summation of elements of new matrix formed

narrayA=np.random.rand(10,20)
print("Array A elements are\n\n",narrayA)
print("Dimension of matrix A:", np.shape(narrayA))

narrayB=np.random.rand(20,25)
print("\nArray B elements are\n\n",narrayB)
print("Dimension of matrix B:", np.shape(narrayB))

#multiplication of matrices using np.dot()
print("\n\n\n Matrix Multiplication\n")
multiplication=np.dot(narrayA,narrayB)
print(multiplication)      
print("Dimension of multiplied matrix is",np.shape(multiplication))

#addition of matrices
summation=np.sum(multiplication)
print("\n\nSum of all the elements of new matrix:", summation)

Array A elements are

 [[0.24930863 0.13025144 0.82885968 0.39804333 0.61782322 0.84926067
  0.53309936 0.24838524 0.01010914 0.41774367 0.28888333 0.40263449
  0.10519594 0.10587456 0.40951514 0.93205166 0.35521621 0.66077211
  0.64315087 0.07302331]
 [0.24772929 0.46931024 0.41259447 0.34302045 0.42243153 0.84891793
  0.62553856 0.1827849  0.67842567 0.78331645 0.05297961 0.95922988
  0.46994382 0.74495098 0.3769782  0.63667335 0.70601548 0.08722889
  0.73447866 0.21138122]
 [0.52538762 0.91225165 0.07244669 0.69182874 0.309779   0.71566126
  0.08922084 0.09399061 0.68816715 0.24203419 0.27240465 0.91948695
  0.76602863 0.78882024 0.46278788 0.0709539  0.67649586 0.2890827
  0.27003138 0.30172368]
 [0.01924773 0.62616083 0.55038423 0.12818106 0.45264843 0.5341595
  0.44802937 0.81929305 0.64190411 0.52823521 0.86725038 0.19005995
  0.97748948 0.29856575 0.32318975 0.03457812 0.45806368 0.06240816
  0.19263705 0.83324259]
 [0.65396977 0.68991217 0.82883716 0.79214232 0.98691437 0.1305

In [55]:
#Question 4
#Applying exp() in the array elements

narray=np.random.rand(10,1)
narrayExp=1/(1+np.exp(-narray))
print("Original array:\n\n",narray)
print("\n\nAfter applying exponential function\n\n",narrayExp)

Original array:

 [[0.4670097 ]
 [0.20336976]
 [0.43761404]
 [0.92559626]
 [0.69669427]
 [0.23389027]
 [0.50129538]
 [0.10384773]
 [0.83534487]
 [0.14215157]]


After applying exponential function

 [[0.61467575]
 [0.55066793]
 [0.60769036]
 [0.71618101]
 [0.66745444]
 [0.55820746]
 [0.6227637 ]
 [0.52593862]
 [0.69748389]
 [0.53547817]]
