[View in Colaboratory](https://colab.research.google.com/github/ditiansm2015/ML-May-28/blob/master/assignment_19.ipynb)

In [0]:
import sklearn
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split 

In [0]:
data = datasets.load_digits()

In [0]:
X = data.data
y = data.target

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40, random_state=42)

In [0]:
from sklearn.cluster import KMeans

In [0]:
clt=KMeans(n_clusters=10)

In [261]:
clt.fit_predict(X_train)

array([6, 8, 4, ..., 6, 6, 9], dtype=int32)

In [0]:
# Declaring a separate variable with size that of Dataset Label(y) and initializing it with 0
y_match=np.zeros_like(y_train)

In [0]:
from scipy import stats

In [0]:
# Using the mode() function to save the most common labels in the label variable(y_match).
for a in range(len(y_train)):
  y_match[a] = stats.mode(y_train[a])[0]

In [0]:
predict_op=clt.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix

In [274]:
con_matrix=confusion_matrix(y_test,predict_op)
print(con_matrix)

[[ 2  3  5  6 12  5  9  7  7 11]
 [ 2  6  6 18  8  8  6  2  8  8]
 [ 3 10  2 14  7  6  9 14  5  8]
 [ 6 13  9  8  5  6  8  8  3 10]
 [ 2  5  6 11  3  9 10  8  3  5]
 [ 3  8  5 14  5  5  5  6 10  5]
 [ 5 11  3 13  6  8  9 11  7  8]
 [ 2  6 10  9 10  5  8  9  8 11]
 [ 2  7  9  9  4  4 12  4  8 11]
 [ 4  4  4  9  7  4 10  6 10 11]]


In [275]:
sklearn.metrics.accuracy_score(y_test, predict_op)

0.08762169680111266